baseURL = 'https://ax86.github.io/freesiteexample/'
languageCode = 'en-us'
title = 'Anapa 2024 - Free Site Example - HUGO'
theme = 'ananke'


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
